import type { GeneratedWorksheet, Problem, Answer } from "./types";
import { getSubcategoryName } from "./categories";

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function escapeLatex(text: string): string {
  // For known plain text (headers, labels) - escape everything
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/%/g, "\\%")
    .replace(/&/g, "\\&")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/\$/g, "\\$")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}");
}

function sanitizeLatexContent(text: string): string {
  // For AI-generated content that mixes LaTeX commands/math with plain text.
  // Strategy: split on math delimiters ($...$), escape only the non-math parts.
  const parts = text.split(/(\$[^$]*\$)/g);
  return parts
    .map((part, i) => {
      // Odd indices are math segments (between $ delimiters)
      if (part.startsWith("$") && part.endsWith("$")) {
        return part; // Leave math untouched
      }
      // Plain text segment — escape special chars but preserve LaTeX commands
      return part
        .replace(/(?<!\\)%/g, "\\%")
        .replace(/(?<!\\)&(?!\\)/g, "\\&")
        .replace(/(?<!\\)#/g, "\\#")
        .replace(/(?<!\\)_(?![{])/g, "\\_");
    })
    .join("");
}

function buildProblemLatex(problem: Problem): string {
  let latex = `\\problem\n${sanitizeLatexContent(problem.content)}\n`;

  if (problem.hasVisual && problem.visualCode) {
    latex += `\n\\begin{center}\n${problem.visualCode}\n\\end{center}\n`;
  }

  if (problem.isGridIn) {
    latex += `\n\\textit{(Student-Produced Response)}\n`;
  } else if (problem.choices) {
    latex += `
\\begin{enumerate}[label=\\Alph*., itemsep=0.3em]
    \\item ${sanitizeLatexContent(problem.choices.A)}
    \\item ${sanitizeLatexContent(problem.choices.B)}
    \\item ${sanitizeLatexContent(problem.choices.C)}
    \\item ${sanitizeLatexContent(problem.choices.D)}
\\end{enumerate}
`;
  }

  return latex;
}

export function buildWorksheetLatex(worksheet: GeneratedWorksheet): string {
  const { problems, metadata } = worksheet;
  const topicName = getSubcategoryName(metadata.category, metadata.subcategory);

  return `\\documentclass[11pt, letterpaper]{article}

% Page geometry
\\usepackage[margin=1in]{geometry}

% Math packages
\\usepackage{amsmath, amssymb}

% Graphics packages
\\usepackage{tikz}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.18}
\\usetikzlibrary{calc, patterns, angles, quotes, positioning}

% Tables
\\usepackage{array}
\\usepackage{booktabs}

% Formatting
\\usepackage{enumitem}
\\usepackage{fancyhdr}
\\usepackage{lastpage}

% URLs
\\usepackage{hyperref}
\\hypersetup{hidelinks}

% Fonts
\\usepackage[T1]{fontenc}

% No paragraph indent
\\setlength{\\parindent}{0pt}

% Fix header height warning
\\setlength{\\headheight}{14pt}

% Header/Footer
\\pagestyle{fancy}
\\fancyhf{}
\\fancyhead[L]{SAT Math Practice --- ${capitalize(metadata.difficulty)}}
\\fancyhead[R]{${escapeLatex(topicName)}}
\\fancyfoot[C]{Page \\thepage\\ of \\pageref{LastPage}}
\\renewcommand{\\headrulewidth}{0.4pt}
\\renewcommand{\\footrulewidth}{0.4pt}

% Problem counter
\\newcounter{prob}

% Problem environment
\\newcommand{\\problem}{%
    \\stepcounter{prob}%
    \\vspace{1.5em}%
    \\textbf{\\theprob.}\\hspace{0.5em}%
}

\\begin{document}

% Title
\\begin{center}
    {\\LARGE\\bfseries SAT Math Practice}\\\\[0.5em]
    {\\large ${escapeLatex(topicName)} --- ${capitalize(metadata.difficulty)}}\\\\[0.3em]
    {${metadata.questionCount} Questions}
\\end{center}

\\vspace{1em}

\\textbf{Directions:} Solve each problem and choose the best answer from the choices provided. For Student-Produced Response questions, solve the problem and enter your answer in the grid. Unless otherwise indicated, assume the following:
\\begin{itemize}[nosep, leftmargin=2em]
    \\item All variables and expressions represent real numbers.
    \\item Figures are drawn to scale unless noted otherwise.
    \\item All figures lie in a plane unless noted otherwise.
\\end{itemize}

\\vspace{1em}
\\hrule
\\vspace{1em}

%%% PROBLEMS %%%
${problems.map((p) => buildProblemLatex(p)).join("\n\\vspace{1em}\n")}

\\vspace{2em}
\\begin{center}
\\rule{0.6\\textwidth}{0.4pt}\\\\[0.8em]
{\\small\\textit{Generated by TKO Prep $|$ tkoprep.com $|$ Free SAT \\& ACT Test Preparation}}
\\end{center}

\\end{document}
`;
}

function buildAnswerLatex(answer: Answer): string {
  const solutionLines = sanitizeLatexContent(answer.solution).split("\\n").join("\n\n");
  return `\\textbf{${answer.number}. ${sanitizeLatexContent(answer.correctAnswer)}}

${solutionLines}
`;
}

export function buildAnswerKeyLatex(worksheet: GeneratedWorksheet): string {
  const { answers, metadata } = worksheet;
  const topicName = getSubcategoryName(metadata.category, metadata.subcategory);

  return `\\documentclass[11pt, letterpaper]{article}

% Page geometry
\\usepackage[margin=1in]{geometry}

% Math packages
\\usepackage{amsmath, amssymb}

% Formatting
\\usepackage{enumitem}
\\usepackage{fancyhdr}
\\usepackage{lastpage}

% URLs
\\usepackage{hyperref}
\\hypersetup{hidelinks}

% Fonts
\\usepackage[T1]{fontenc}

% No paragraph indent
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0.5em}

% Fix header height warning
\\setlength{\\headheight}{14pt}

% Header/Footer
\\pagestyle{fancy}
\\fancyhf{}
\\fancyhead[L]{Answer Key}
\\fancyhead[R]{${escapeLatex(topicName)}}
\\fancyfoot[C]{Page \\thepage\\ of \\pageref{LastPage}}
\\renewcommand{\\headrulewidth}{0.4pt}
\\renewcommand{\\footrulewidth}{0.4pt}

\\begin{document}

% Title
\\begin{center}
    {\\LARGE\\bfseries Answer Key}\\\\[0.5em]
    {\\large ${escapeLatex(topicName)} --- ${capitalize(metadata.difficulty)}}\\\\[0.3em]
    {${metadata.questionCount} Questions}
\\end{center}

\\vspace{1em}
\\hrule
\\vspace{1em}

%%% ANSWERS %%%
${answers.map((a) => buildAnswerLatex(a)).join("\n\\hrule\n\\vspace{0.5em}\n")}

\\vspace{2em}
\\begin{center}
\\rule{0.7\\textwidth}{0.4pt}\\\\[0.8em]
{\\small\\textit{Need help mastering these concepts? Book a free consultation at \\textbf{tkoprep.com}}}
\\end{center}

\\end{document}
`;
}
